version: '3'

services:
  yake:
    image: amsdard.io/yake/yake
    build:
        context: ./
        dockerfile: ./doc/docker/Dockerfile
    networks:
      - global
    container_name: yake.amsdard.io
    labels:
      - "traefik.frontend.rule=Host:yake.amsdard.io.app"

networks:
  global:
    external: true