version: '2'

services:
  yake:
    image: amsdard.io/yake/yake
    build:
        context: ./
        dockerfile: ./doc/docker/Dockerfile
    network_mode: "bridge"
    container_name: yake.amsdard.io
    environment:
       - VIRTUAL_HOST=yake.app